name: Testing self-hosted-mac-runner
on:
  workflow_dispatch:
  push:

jobs:
  testing:
    name: self-hosted mac-runner
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: list ls
        run: ls -l && sleep 300
