name: Testing self-hosted-mac-runner
on:
  workflow_dispatch:
  push:

jobs:
  testing:
    runs-on: [self-hosted, test, macOS]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: list ls
        run: ls -l
