name: Testing self-hosted-mac-runner
on:
  workflow_dispatch:
  push:

jobs:
  testing:
    runs-on: [self-hosted, test, macOS]
    steps:
      - name: ECHO Contents
        run: |
          echo OK
          sleep 15s
