name: Vault demo
on:
  dispatch-workflow:

jobs:
  echo-vault-secret:
    name: Vault Secret 
    runs-on: ubuntu-latest
    steps:
      - name: Testing Secrets
        run: |
          if [[ -z "${{ secrets.AWS_API_KEY }}" ]]; then
            echo "Secret Not Found"
            exit 1
          else
            echo "Secret Found"
            exit 0
          fi


               
        